import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { Providers } from './Providers'
import '@/styles/globals.scss'
import { Layout } from '@/components'

const plusJakartsSansFont = Plus_Jakarta_Sans({
	subsets: ['latin'],
	fallback: ['montserrat']
})

export const metadata: Metadata = {
	title: 'Furniro E-commerce app',
	description: 'Generated by Furniro E-commerce app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<Providers>
			<html lang='en'>
				<body className={plusJakartsSansFont.className}>
					<Layout heroBg>{children}</Layout>
				</body>
			</html>
		</Providers>
	)
}
