import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { Toaster, ToasterProps } from 'react-hot-toast'

import { Layout } from '@/components'
import { Providers } from './Providers'

import '@/styles/globals.scss'

const plusJakartsSansFont = Plus_Jakarta_Sans({
	subsets: ['latin'],
	fallback: ['montserrat']
})

const toasterProps: ToasterProps = {
	position: 'top-right',
	toastOptions: {
		style: {
			fontSize: '0.875rem'
		},
		duration: 5000,
		success: {
			style: {
				backgroundColor: '#DCFCE7',
				color: '#14532D'
			}
		}
	}
}

export const metadata: Metadata = {
	title: 'Furniro E-commerce app',
	description: 'Generated by Furniro E-commerce app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<Providers>
			<html lang='en'>
				<body className={plusJakartsSansFont.className}>
					<Toaster {...toasterProps} />
					<Layout>{children}</Layout>
				</body>
			</html>
		</Providers>
	)
}
